here is the book challenge
waldenwang9966/Pod4_repo pull request #73
Opened 2022-03-15 00:17 UTC by Dave218

couldn't finish the bonus. couldn't figure out how to do the "display"

2022-03-15 01:44 UTC, waldenwang9966 requested changes

2022-03-15 01:44 UTC, waldenwang9966 commented on David/book_list_class.py
> +		titles = self
This is incorrect. Think about how you should initialize the titles.

2022-03-15 01:44 UTC, waldenwang9966 commented on David/book_list_class.py
> +			titles.sort()
Where should you put the sort?

2022-03-15 01:44 UTC, waldenwang9966 commented on David/book_list_class.py
> +
if len() == 0: return True else return False

2022-03-16 16:02 UTC, Dave218 commented
got it working. Thanks!

2022-03-16 16:08 UTC, waldenwang9966 approved these changes

2022-03-16 16:08 UTC, merged